package:
  name: viewshed
  version: "0.7.6"

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja 
  host:
    - python
    - pybind11
    - pybind11-stubgen
    - libgdal
    - libsimplerasters
    - libviewshed
  run:
    - python
    - libviewshed
    - libsimplerasters

test:
  imports:
    - viewshed
  commands:
    - python -c "import viewshed; print(viewshed.__version__)"
  requires:
    - pytest

about:
  home: https://github.com/JanCaha/viewshed-library-pybind11
  license: MIT
  summary: "Minimalistic python interface for C++ library viewshed. Makes running examples and experiments much easier"

extra:
  recipe-maintainers:
    - JanCaha
  channels:
    - conda-forge
