name: Build conda package

on: push

jobs:

  Update-conda-package-version:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Set Env variable with project version
        run: |
            python_package_version=$(grep '^version = ' pyproject.toml | sed -E 's/version = "([0-9]+\.[0-9]+\.[0-9]+)"/\1/')
            echo "PROJECT_VERSION=$python_package_version" >> $GITHUB_ENV
      
      - name: Print project version
        run: |
            echo "Project version: $PROJECT_VERSION"
            
      - name: Set project version
        run: |
            sed -i '/^project(/s/[0-9]\+\.[0-9]\+\.[0-9]\+/'$PROJECT_VERSION'/' CMakeLists.txt

      - name: Update conda package version
        run: |
          sed -i '/version: /c\  version: \"'$PROJECT_VERSION'\"' conda/meta.yaml
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: Change to conda package version
            file_pattern: 'conda/meta.yaml'

  Build-on-Linux:

    name: Build on Linux

    runs-on: ubuntu-latest

    needs: Update-conda-package-version

    defaults:
      run:
        shell: bash -l {0}

    permissions:
      contents: write

    env:
      CONDA_PKG_DIR: ~/conda_pkgs_dir
      GH_TOKEN: ${{ github.token }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          use-mamba: true
          channels: conda-forge,defaults
          auto-activate-base: true
          activate-environment: ""

      - name: Add Custom Conda Channel
        run: |
          conda config --add channels https://jancaha.github.io/conda-channel

      - name: Install conda-build
        run: |
          conda install -n base conda-build conda-verify

      - name: Build library
        run: |
          conda build conda --output-folder conda_package
      
      - name: Upload artifact   
        uses: actions/upload-artifact@v4
        with:
          path: conda_package/linux-64/*.conda 
          name: conda_package_linux