name: Release Docker

on:
  workflow_run:
    workflows: ["Test package"]
    types:
      - completed
    branches:
      - 'main'
      - 'master'
  push:
    branches:
      - 'main'
      - 'master'
    paths:
      - src/**
      - src_python/**
      - pyproject.toml
      - .github/wrokflows/release_docker.yaml
      
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
jobs:

  Release-Docker:

    runs-on: ubuntu-latest

    steps:

        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: true

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image latest
          uses: docker/build-push-action@v5
          with:
            file: docker/Dockerfile
            context: docker/
            push: true
            tags: cahik/viewshed:latest-python