name: Test package

on:
  push:
    paths:
      - src/**
      - tests/**
      - setup.py
      - setup.cfg
      - CMakeLists.txt
      - .github/workflows/test_package.yaml

jobs:

  Run-Test:

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    name: "Test package in Python ${{ matrix.python-version }}"

    runs-on: ubuntu-latest

    steps:

      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: 'x64'

      - name: Install requirments
        run: |
          sudo add-apt-repository ppa:jancaha/gis-tools
          sudo apt-get update
          sudo apt-get install viewshed-bin
      
      - name: Install pip packages
        run: |
          pip install wheel pytest

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install package
        run: |
          python3 setup.py bdist_wheel
          pip install dist/viewshed-*.whl --force-reinstall

      - name: Run tests
        run: pytest -vv -s
      
      - uses: actions/upload-artifact@v3
        if: "contains(${{ matrix.python-version }}, '3.10')"
        with:
          name: viewshed
          path: dist/viewshed*.whl
  
  Release-Docker:

    runs-on: ubuntu-latest

    needs: Run-Test

    steps:

        - name: Checkout
          uses: actions/checkout@v3
          with:
            submodules: true

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Set Env and GA Output
          id: version
          run: |
            echo "VERSION=$(grep "version = " setup.cfg | grep -E -o -e "[0-9\.]+")" >> $GITHUB_ENV
            echo "VERSION=$(grep "version = " setup.cfg | grep -E -o -e "[0-9\.]+")" >> $GITHUB_OUTPUT
        
        - name: Build and push Docker image latest
          uses: docker/build-push-action@v4
          with:
            file: docker/Dockerfile
            context: docker/
            push: true
            tags: cahik/viewshed:latest-python
