name: Test package

on:
  push:
    paths:
      - src/**
      - tests/**
      - setup.py
      - setup.cfg
      - pyproject.toml
      - CMakeLists.txt
      - .github/workflows/test_package.yaml

jobs:

  Run-Test:

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    name: "Test package in Python ${{ matrix.python-version }}"

    runs-on: ubuntu-latest

    steps:

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: 'x64'
       
      - name: Install GDAL
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt update
          sudo apt-get -y install gdal-bin libgdal-dev

      - name: Install pybind11
        run: |
          sudo apt-get install pybind11-dev python3-pybind11

      - name: Install requirments
        run: |
          sudo add-apt-repository ppa:jancaha/gis-tools
          sudo apt-get update
          sudo apt-get install viewshed-bin
      
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Install pip packages
        run: |
          pip install wheel py-build-cmake build pytest

      - name: Install package
        run: |
          pip install .
          python -m build .

      - name: Run tests
        run: pytest -vv -s
      
      - name: List files
        run: |
          ls -l    
          cd dist
          ls -l 
  
      - uses: actions/upload-artifact@v4
        with:
          name: viewshed-${{ matrix.python-version }}
          path: dist/viewshed*.whl

