name: Test package

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - src/**
      - cpp_module/**
      - tests/**
      - pyproject.toml
      - CMakeLists.txt
      - .github/workflows/test_package.yaml

jobs:

  Run-Test:

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    name: "Test package in Python ${{ matrix.python-version }}"

    runs-on: ubuntu-latest
    
    env:
      CXX: clang++
      CC: clang
  
    steps:

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: 'x64'
       
      - name: Install GDAL
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt update
          sudo apt-get -y install gdal-bin libgdal-dev clang

      - name: Install pybind11
        run: |
          sudo apt-get install pybind11-dev python3-pybind11

      - uses: robinraju/release-downloader@v1
        with:
          repository: "JanCaha/cpp-simplerasters"
          latest: true
          fileName: "*.deb"
          tarBall: false
          zipBall: false
        
      - uses: robinraju/release-downloader@v1
        with:
          repository: "JanCaha/cpp-viewshed-library"
          latest: true
          fileName: "viewshed-no-qt*.deb"
          tarBall: false
          zipBall: false

      - name: Install and remove artifact
        run: |
          sudo apt install ./simplerasters*.deb
          rm simplerasters*

      - name: Install and remove artifact
        run: |
          sudo apt install ./viewshed-no-qt*.deb
          rm viewshed*
      
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install pip packages
        run: |
          pip install wheel build pytest

      - name: Install package
        run: |
          pip install .
          python -m build .

      - name: Run tests
        run: pytest -vv -s
      
      - name: List files
        run: |
          ls -l    
          cd dist
          ls -l 
  
      - uses: actions/upload-artifact@v4
        with:
          name: viewshed-${{ matrix.python-version }}
          path: dist/viewshed*.whl

