name: Test package

on:
  push:
    paths:
      - src/**
      - tests/**
      - setup.py
      - setup.cfg
      - CMakeLists.txt
      - .github/workflows/test_package.yaml

jobs:

  Run-Test:

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    name: "Test package in Python ${{ matrix.python-version }}"

    runs-on: ubuntu-latest

    steps:

      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: 'x64'

      - name: Install requirments
        run: |
          sudo add-apt-repository ppa:jancaha/gis-tools
          sudo apt-get update
          sudo apt-get install viewshed-bin
      
      - name: Install pip packages
        run: |
          pip install wheel pytest py-build-cmake

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install package
        run: |
          pip install build
          pip install .

      - name: Run tests
        run: pytest -vv -s
      
      - uses: actions/upload-artifact@v3
        if: "contains(${{ matrix.python-version }}, '3.10')"
        with:
          name: viewshed
          path: dist/viewshed*.whl

